//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisVlaanderen_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonnement
    {
        public int Id { get; set; }
        public int SpelerID { get; set; }
        public int ClubID { get; set; }
        public string Lessen { get; set; }
        public string Stages { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Speler Speler { get; set; }
    }
}
