//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisVlaanderen_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Club()
        {
            this.Abonnement = new HashSet<Abonnement>();
            this.Tarieven = new HashSet<Tarieven>();
            this.SpelerClubTornooi = new HashSet<SpelerClubTornooi>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public string Adres { get; set; }
        public string Telefoon { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string KwaliteitLabel { get; set; }
        public string Clubaanbod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonnement> Abonnement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarieven> Tarieven { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpelerClubTornooi> SpelerClubTornooi { get; set; }
    }
}
