//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisVlaanderen_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpelerClubTornooi
    {
        public int id { get; set; }
        public int clubID { get; set; }
        public int spelerID { get; set; }
        public int tornooiID { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Speler Speler { get; set; }
        public virtual Tornooi Tornooi { get; set; }
    }
}
