//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisVlaanderen_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Speler()
        {
            this.Abonnement = new HashSet<Abonnement>();
            this.SpelerClubTornooi = new HashSet<SpelerClubTornooi>();
            this.TerreinReservatie = new HashSet<TerreinReservatie>();
        }
    
        public int id { get; set; }
        public string naam { get; set; }
        public string voornaam { get; set; }
        public string klassement { get; set; }
        public string geslacht { get; set; }
        public System.DateTime geboorteDatum { get; set; }
        public string nationaliteit { get; set; }
        public string adres { get; set; }
        public string land { get; set; }
        public string telefoon { get; set; }
        public string email { get; set; }
        public string rijksNummer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonnement> Abonnement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpelerClubTornooi> SpelerClubTornooi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerreinReservatie> TerreinReservatie { get; set; }
    }
}
