//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisVlaanderen_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarieven
    {
        public int Id { get; set; }
        public int ClubID { get; set; }
        public string Leeftijdgraad { get; set; }
        public string TypeTennis { get; set; }
        public Nullable<decimal> Prijs { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
