//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisVlaanderen_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PublishersEntities2 : DbContext
    {
        public PublishersEntities2()
            : base("name=PublishersEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonnement> Abonnement { get; set; }
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<Speler> Speler { get; set; }
        public virtual DbSet<SpelerClubTornooi> SpelerClubTornooi { get; set; }
        public virtual DbSet<Tarieven> Tarieven { get; set; }
        public virtual DbSet<TerreinReservatie> TerreinReservatie { get; set; }
        public virtual DbSet<Tornooi> Tornooi { get; set; }
    }
}
