//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisVlaanderen_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tornooi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tornooi()
        {
            this.SpelerClubTornooi = new HashSet<SpelerClubTornooi>();
        }
    
        public int id { get; set; }
        public string naamTornooi { get; set; }
        public System.DateTime datum { get; set; }
        public string circuit { get; set; }
        public string typeCompetitie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpelerClubTornooi> SpelerClubTornooi { get; set; }
    }
}
